### ISSUE TITLE
Inconsistent parameter name for email address

### ISSUE THREAD

**Issue by leockl** [alessandriniluca/postget#1]
**Reproducible Example**
Not Applicable.

**Issue Description**
The parameter name for email address appears to be inconsistent in different files. 

The parameter name in the main.py file is called `mail`. The parameter name in the Posts.py file is called `email_address`,

This doesn't appear to be triggering any errors after running the script though.

**Expected Behavior**
Expect same parameters to have the same parameter names for consistency.

**Installed Versions**
postget-1.1.1
Chromedriver 113.0.5672.63
Chromium 117.0.5904.0
Python 3.10.9
Conda 23.3.1
Windows 11

**Extra Discription**
None.

**Comment by alessandriniluca** [comment]
You're correct, thank you for pointing it out.
I confirm that this seems not triggering any error, I am marking this as documentation to let everyone know that this should not cause problems, it is only an inconsistency in the parameter naming.
I've linked the branch with the fix, if you please can confirm that now everything is ok, I'll merge it into the develop branch.
If I'm missing something, let me know!

**Comment by leockl** [comment]
Yup, this is ok now. The parameter is now consistently called `email_address`. Thanks!

**Comment by alessandriniluca** [comment]
Perfect, I'm closing the issue right now and merging into the develop branch
